### ISSUE TITLE
Exogenous variable in the Volatility Equation

### ISSUE THREAD

**Issue by filanarfahz** [bashtage/arch#635] opened 2023-04-03 12:38 UTC
I was wondering if it is possible to include an exogenous covariate in the volatility equation. Currently, the example shows the addition of an exogenous covariate in the mean equation, but not in the volatility equation.

**Comment by bashtage** [comment] 2023-05-26 10:53
Closing as a duplicate of #160

**Closed by bashtage** 2023-05-26 10:53 UTC
