### ISSUE TITLE
Multithreading fit ARX causing The optimizer returned code 9

### ISSUE THREAD

**Issue by gaussleescorpio** [bashtage/arch#123] opened 2016-08-10 09:53 UTC
Hi, I recently start to use your library for modelling time series. It works perfectly fine under single thread. But if I use ARX model and fit a lot of them in a multithreading task. Then I randomly got either

`The optimizer returned code 9. The message is:
Iteration limit exceeded
See scipy.optimize.fmin_slsqp for code meaning.

  ConvergenceWarning)`

or `The optimizer returned code 5` problems. So I get nan for the final results. Is it normal? Is ARX thread safe?

**Comment by bashtage** [comment] 2016-08-10 10:06
This is something that I have never considered.  This issue is that there
is a module level variable that stores the iteration count that is accessed
inside the likelihood as a global and incremented.  Having many threads
will obviously cause problems.  The solution would be to use a class-level
variable which would work.

**Comment by gaussleescorpio** [comment] 2016-08-10 10:49
@bashtage : Thanks for your replies. Yes. That definitely is the reason. I think it is very possible to use your model in a multithreaded way from the user point of view. Do you think it can be a quick fix? Which variable I should change from global to class level?

**Comment by bashtage** [comment] 2016-08-10 10:56
Could you post a small example showing the problem?  It will help in making
a test.

**Comment by gaussleescorpio** [comment] 2016-08-10 11:03
Here is my example code:
`  from arch.univariate import ARX, GARCH
    from Queue import Queue
    from threading import Thread
    import time

    def batch_learning(X, lag_array=None):
        """
        X is the time series input, and lag_array is a list composed of all the num of lags to be cross         validated
        """
        tmp = []
        tmp_res = []
        queue = Queue()
        data = []
        def ARX_fit(queue):
            while True:
                num = queue.get()
                q = ARX(X, lags=num)
                q.volatility = GARCH()
                print q.lags
                print "Starting to fit lags %s" %str(q.lags.size/2)
                try:
                    q_res=q.fit(update_freq=0, disp="final")
                except:
                    print "Error:...."
                data.append((q_res.aic + q_res.bic, q_res))
                tmp.append(q_res.aic + q_res.bic)
                tmp_res.append(q_res)
                print "finished lags %s" %str(q.lags.size/2)
                queue.task_done()
        #creating 2 threads here
        for i in range(2):
            thread_i = Thread(target=ARX_fit, name="Thread_%s"%str(i), args=(queue,))
            ps.append(thread_i)
            thread_i.start()

        for num in lag_array:
            queue.put(num)

        queue.join()
        return`

When I run `batch_learning(a, lag_array=range(1,10))`,  threads will fail to converge or have singularity problem like below:
`The optimizer returned code 9. The message is:
Iteration limit exceeded
See scipy.optimize.fmin_slsqp for code meaning.ConvergenceWarning)`
Or `The optimizer returned code 5. The message is:
Singular matrix E in LSQ subproblem
See scipy.optimize.fmin_slsqp for code meaning. ConvergenceWarning)`

**Comment by bashtage** [comment] 2016-08-10 11:20
Thanks.  Do you see the same problem when you run with 1 thread (or ideally
without threading)?

On the surface I wouldn't expect large gains usng multithreading since I
don't explicitly release the GIL anywhere.  Normally in these circumstances
multiprocessing (or the simple inferface in joblib) is usually used and
this should scale well and will probably not have the same issues as
multithreading since things are pickled across processes and not explicitly
shared.

**Comment by gaussleescorpio** [comment] 2016-08-10 11:25
@bashtage With one single thread, it works fine. Problems happened when there 2 or more threads. Multiprocessing actually runs perfectly indeed.

**Comment by bashtage** [comment] 2016-08-10 11:30
Thanks.  

```
from queue import Queue
from threading import Thread

import numpy as np
from arch.univariate import ARX, GARCH

ps = []


def batch_learning(x, lag_array=None):
    """
    X is the time series input, and lag_array is a list composed of all the num of lags to be cross
    validated
    """
    tmp = []
    tmp_res = []
    queue = Queue()
    data = []

    def arx_fit(queue):
        while True:
            num = queue.get()
            q = ARX(x, lags=num)
            q.volatility = GARCH()
            print(q.lags)
            print("Starting to fit lags {0}".format(q.lags.size / 2))
            try:
                q_res = q.fit(update_freq=0, disp="final")
            except:
                print("Error:....")
            data.append((q_res.aic + q_res.bic, q_res))
            tmp.append(q_res.aic + q_res.bic)
            tmp_res.append(q_res)
            print("finished lags {0}".format(str(q.lags.size / 2)))
            queue.task_done()

    # creating 2 threads here
    for i in range(2):
        thread_i = Thread(target=arx_fit, name="Thread_%s" % str(i), args=(queue,))
        ps.append(thread_i)
        thread_i.start()

    for num in lag_array:
        queue.put(num)

    queue.join()
    return


if __name__ == '__main__':
    q = ARX(lags=3)
    q.volatility = GARCH()
    data = q.simulate(np.array([10, 1.5, -0.9, 0.2, 0.1, 0.05, 0.85]), 5000)
    # batch_learning(data['data'], np.arange(1, 11))
    for lags in range(1, 11):
        q = ARX(data['data'], lags=lags)
        q.volatility = GARCH()
        print(q.lags)
        print("Starting to fit lags {0}".format(q.lags.size / 2))
        try:
            q_res = q.fit(update_freq=0, disp="final")
        except:
            print("Error:....")


```
shows exactly what you said.  I'm not totally sure if it is me or in fact scipy.optimize that isn't thread safe.  For clarity, I'm sure `arch` is not TS, but I'm sure note `scipy.optimize` is TS

**Comment by gaussleescorpio** [comment] 2016-08-10 11:37
@bashtage  Yes. I think arch is not TS as well. Scipy.optimize should be TS according to my knowledge. My plan is not to use python multithreading finally. I am only testing it. I plan to use Cython to get around GIL. If arch is not TS, there is no guarantee it will work. Do you think it is worth fixing it? I think I can use multiprocessing temporally now.

**Comment by bashtage** [comment] 2016-08-10 11:39
It could be - if the problem is in `arch` I suspect it should be a easy
enough.  What makes me suspect scipy is that I think the variable that
holds the iteration limit that is used by the optimizer is provided by
`scipy`.

**Comment by gaussleescorpio** [comment] 2016-08-10 11:43
Look at this guy's post: 
[here](http://stackoverflow.com/questions/4598339/parallelism-with-scipy-optimize). It seems scipy.optimize is not thread safe.

**Comment by bashtage** [comment] 2016-08-10 11:44
Thanks for the pointer.  I'll leave this open as it woudl be good to move away from module level variables if possible.

**Comment by gaussleescorpio** [comment] 2016-08-10 11:48
@bashtage Thanks for your clarity. I hope this can be fixed somehow. It seems using a mutex lock to where scipy.optimizer is used can be helpful according to the link.

**Comment by bashtage** [comment] 2016-08-10 11:51
The Lock will work but you will only get single threaded performance.  So
gains with that approach.  I suspect that scipy.optimize was never intended
for threaded use.  There are some github issues about this on scipy.
Multiprocessing is almost always the way to go since lots of (most??)  code
doesn't release the GIL.

**Comment by gaussleescorpio** [comment] 2016-08-12 13:00
@bashtage Hi, again. I solved the multithreading problem using python multiprocessing which actually can avoid GIL problem. However, it always give me this warning:

``
The optimizer returned code 9. The message is:
Iteration limit exceeded
See scipy.optimize.fmin_slsqp for code meaning.

  ConvergenceWarning)``

Do you know under what conditions it can cause this warning? I am just fitting a ARX model with lag > 90 with a Garch model on my time series. It always gave me this warning even you run them in a single process without forking.

**Comment by bashtage** [comment] 2016-08-12 13:22
I suspect that the scipy optimize isn't going well with numerical derivatives with ~100 parameters (assuming you really meant lag > 90 -- I'm not sure what type of process would ever need 90 lags until there were 1000000s of data points, and even then...)

Kevin

**Comment by bashtage** [comment] 2016-12-22 10:26
I'm going to close this since I don't think there is much I can do about it since it is upstream in scipy.

**Closed** 2016-12-22 10:27 UTC
